name: medi_care3
description: "A medicine reminder Flutter application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  animate_do: ^3.1.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  email_validator: ^2.1.17
  crypto: ^3.0.3
  get: ^4.7.2
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true